# Generated by Django 3.2.4 on 2022-11-26 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_categories_category_rename_images_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='IPhone 14 Pro Max', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.image'),
            preserve_default=False,
        ),
    ]
