# Generated by Django 4.1.3 on 2022-12-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_special_off_specialoff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='link',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='link',
        ),
        migrations.RemoveField(
            model_name='category',
            name='link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='link',
        ),
    ]
