# Generated by Django 3.2.4 on 2022-11-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
