# Generated by Django 4.1.2 on 2022-11-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_laptop_mobile_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
