# Generated by Django 4.1.2 on 2022-11-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_laptop_price_alter_laptop_ram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu_serie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='graphic_brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='link',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='resolution',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='camera_resolution',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='display_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='link',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='os',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='size',
            field=models.FloatField(),
        ),
    ]
