# Generated by Django 4.1.2 on 2022-11-27 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_laptop_brand_laptop_category_mobile_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(default='Laptop', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.ForeignKey(default='Mobile', on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
