# Generated by Django 4.1.2 on 2022-11-28 05:19

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_laptop_brand_alter_laptop_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='images',
            field=django_mysql.models.ListCharField(models.CharField(default='mmd', max_length=255), blank=True, max_length=255, size=None),
        ),
        migrations.AddField(
            model_name='mobile',
            name='images',
            field=django_mysql.models.ListCharField(models.CharField(default='mmd', max_length=255), blank=True, max_length=255, size=None),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
