# Generated by Django 4.1.2 on 2022-11-28 05:20

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_laptop_images_mobile_images_alter_laptop_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='images',
            field=django_mysql.models.ListCharField(models.CharField(default='a', max_length=255), default=['a'], max_length=255, size=None),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='images',
            field=django_mysql.models.ListCharField(models.CharField(default='a', max_length=255), default=['a'], max_length=255, size=None),
        ),
    ]
