# Generated by Django 4.1.2 on 2022-11-28 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_laptop_images_alter_mobile_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='images',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='images',
        ),
    ]
