# Generated by Django 3.2.4 on 2022-11-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_laptop_image_remove_mobile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mobile',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
