# Generated by Django 4.1.2 on 2022-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20221128_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mobile',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
