# Generated by Django 4.1.2 on 2022-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_advertise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertise',
            new_name='Review',
        ),
    ]
