# Generated by Django 4.1.2 on 2022-11-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_advertise_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Header',
        ),
    ]
