# Generated by Django 4.1.2 on 2022-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_rename_review_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Off',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('off', models.SmallIntegerField()),
                ('detail_1', models.CharField(max_length=50)),
                ('detail_2', models.CharField(max_length=50)),
                ('detail_3', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='link',
            field=models.CharField(default='', max_length=50),
        ),
    ]
