# Generated by Django 4.1.2 on 2022-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_special_off_header_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_off',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
