# Generated by Django 4.1.2 on 2022-11-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image',
        ),
    ]
