# Generated by Django 4.1.2 on 2022-11-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_rename_name_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='category',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='count',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='images',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='link',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='count',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='images',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='link',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='price',
        ),
        migrations.AddField(
            model_name='laptop',
            name='laptop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='mobile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
