# Generated by Django 4.1.2 on 2022-11-30 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_laptop_brand_remove_laptop_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='laptop',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
