# Generated by Django 4.1.3 on 2022-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_remove_header_link_remove_header_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='views',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='views',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
