# Generated by Django 4.1.3 on 2022-12-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_remove_laptop_views_remove_mobile_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='laptop',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='mobile',
            new_name='product',
        ),
    ]
